1

diff --git a/.github/workflows/4testing-build.yml b/.github/workflows/4testing-build.yml
--- a/.github/workflows/4testing-build.yml
+++ b/.github/workflows/4testing-build.yml
@@ -53,32 +53,60 @@ jobs:
         run: |
           DOCKER_TAG=$(echo ${{ env.RELEASE_VERSION }} | sed 's/^.//' )
           PACKAGE_VERSION=$( echo $DOCKER_TAG | sed -E 's/(.*)\./\1-/' )
-          PACKAGE_URL=${{ secrets.REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_amd64.deb
-          STATUS=$(curl -s -o /dev/null -w "%{http_code}\n" "$PACKAGE_URL")
+          if [[ ${{ env.RELEASE_VERSION }}  == v99.99* ]]; then 
+             sed -i "s|http://download.onlyoffice.com/install/documentserver/linux/\${COMPANY_NAME}-\${PRODUCT_NAME}\${PRODUCT_EDITION}|${{ secrets.UNSTABLE_REPO_URL }}${{ matrix.edition }}_$PACKAGE_VERSION|g" Dockerfile
+             PACKAGE_URL=${{ secrets.UNSTABLE_REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_amd64.deb
+          else 
+            sed -i "s|http://download.onlyoffice.com/install/documentserver/linux/\${COMPANY_NAME}-\${PRODUCT_NAME}\${PRODUCT_EDITION}|${{ secrets.REPO_URL }}${{ matrix.edition }}_$PACKAGE_VERSION|g" Dockerfile
+             PACKAGE_URL=${{ secrets.REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_amd64.deb
+          fi
+             STATUS=$(curl -s -o /dev/null -w "%{http_code}\n" "$PACKAGE_URL")
           if [[ "$STATUS" = "200" ]]; then
              echo "Have access to documentserver${{ matrix.edition }} amd64 arch >> check arm64 access"
+             AMD64=present
           else 
              echo "FAILED: Have no access to documentserver${{ matrix.edition }} amd64 arch"
-             exit 1
+             AMD64=
           fi
-          PACKAGE_URL=${{ secrets.REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_arm64.deb
+          if [[ ${{ env.RELEASE_VERSION }}  == v99.99* ]]; then
+             PACKAGE_URL=${{ secrets.UNSTABLE_REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_arm64.deb
+          else
+             PACKAGE_URL=${{ secrets.REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_arm64.deb 
+          fi
           STATUS=$(curl -s -o /dev/null -w "%{http_code}\n" "$PACKAGE_URL") 
           if [[ "$STATUS" = "200" ]]; then
              echo "Have access to documentserver${{ matrix.edition }} arm64 arch"
-             echo "All architecture are available >> build is starting."
-             sed -i "s|http://download.onlyoffice.com/install/documentserver/linux/\${COMPANY_NAME}-\${PRODUCT_NAME}\${PRODUCT_EDITION}|${{ secrets.REPO_URL }}${{ matrix.edition }}_$PACKAGE_VERSION|g" Dockerfile
-             PRODUCT_EDITION=${{ matrix.edition }} \
-                PRODUCT_NAME=${{ env.PRODUCT_NAME }} DOCKERFILE=Dockerfile \
-                PREFIX_NAME=4testing- TAG=$DOCKER_TAG \
-                docker buildx bake \
-                -f docker-bake.hcl ${{ matrix.images }} \
-                --push
+             ARM64=present
+          else
+             ARM64=
+          fi
+          
+          if [[ "$AMD64" = "present" ]] && [[ "$ARM64" = "present" ]]; then
+            PLATFORMS="--set *.platform=linux/amd64,linux/arm64"
+          fi
+
+          if [[ "$AMD64" != "present" ]] && [[ "$ARM64" = "present" ]]; then
+            PLATFORMS="--set *.platform=linux/arm64"
+          fi
+
+          if [[ "$AMD64" = "present" ]] && [[ "$ARM64" != "present" ]]; then
+            PLATFORMS="--set *.platform=linux/amd64"
+          fi
+
+          if [[ "$AMD64" != "present" ]] && [[ "$ARM64" != "present" ]]; then
+            echo "FAILED: Build will not started requested architectures does not present"
+            exit 1
+          fi
+          echo "Start build >>"     
+          PRODUCT_EDITION=${{ matrix.edition }} \
+            PRODUCT_NAME=${{ env.PRODUCT_NAME }} DOCKERFILE=Dockerfile \
+            PREFIX_NAME=4testing- TAG=$DOCKER_TAG \
+            docker buildx bake \
+             -f docker-bake.hcl ${{ matrix.images }} \
+             <<< """$PLATFORMS""" \ 
+             --push
              echo "DONE: Build success >> exit with 0"
              exit 0  
-          else
-             echo "FAILED: Have no access to some required architecture documentserver${{ matrix.edition }} >> Exit with 0."
-             exit 1
-          fi
         shell: bash
 
   build-unstable:
@@ -124,7 +152,7 @@ jobs:
           else
              AMD64=
           fi
-          PACKAGE_URL=${{ secrets.REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_arm64.deb
+          PACKAGE_URL=${{ secrets.UNSTABLE_REPO_URL }}${{ matrix.edition }}_"$PACKAGE_VERSION"_arm64.deb
           STATUS=$(curl -s -o /dev/null -w "%{http_code}\n" "$PACKAGE_URL")
           if [[ "$STATUS" = "200" ]]; then
              echo "Have access to documentserver${{ matrix.edition }} arm64 arch"
